trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
    displayName: 'Install dependencies'

  - script: |
      npm run lint
    displayName: 'Lint'

  - script: |
      npm run prettier:check
    displayName: 'Check formatting'

  - script: |
      npm run test:coverage
    displayName: 'Run tests with coverage'

  - script: |
      npm run build
    displayName: 'Build'

  - task: Docker@2
    inputs:
      containerRegistry: '<your-container-registry-connection>'
      repository: '<your-docker-repository>'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest
    displayName: 'Build and push Docker image'
